import bcrypt from 'bcryptjs';
import {
  Tenant,
  User,
  Category,
  Collection,
  Product,
  Bundle,
  HomepageSection,
  NavigationItem,
  FooterColumn,
  ThemeSettings,
  PaymentIntegration,
  Promotion,
  Testimonial,
  BlogPost,
  SiteSettings,
  Order,
  AnalyticsEvent,
  MediaItem,
  AdminActivity,
} from '../types';

export function getInitialSeedData(): {
  tenants: Tenant[];
  users: User[];
  categories: Category[];
  collections: Collection[];
  products: Product[];
  bundles: Bundle[];
  homepageSections: HomepageSection[];
  navigationItems: NavigationItem[];
  footerColumns: FooterColumn[];
  themeSettings: ThemeSettings;
  paymentIntegrations: PaymentIntegration[];
  promotions: Promotion[];
  testimonials: Testimonial[];
  blogPosts: BlogPost[];
  siteSettings: SiteSettings;
  orders: Order[];
  analyticsEvents: AnalyticsEvent[];
  mediaItems: MediaItem[];
  adminActivity: AdminActivity[];
} {
  const tenantDemo: Tenant = {
    id: 'tenant_demo',
    slug: 'demo',
    storeName: 'My GumShop Store',
    tagline: 'Premium Lifestyle & Tech Gear',
    ownerEmail: 'admin@gumshop.online',
    ownerName: 'Store Admin',
    plan: 'free',
    productLimit: 10,
    gumroadStoreUrl: 'https://manmeetraj6.gumroad.com',
    primaryColor: '#6366F1',
    currency: 'USD',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isActive: true,
  };

  const users: User[] = [
    {
      id: 'usr_admin_1',
      tenantId: 'tenant_demo',
      email: 'admin@gumshop.online',
      name: 'Store Admin',
      role: 'superadmin',
      createdAt: new Date().toISOString(),
      password: bcrypt.hashSync(process.env.ADMIN_PASSWORD || 'admin123', 10),
    },
    {
      id: 'usr_superadmin_1',
      tenantId: 'tenant_demo',
      email: 'superadmin@gumshop.online',
      name: 'GumShop Super Admin',
      role: 'superadmin',
      createdAt: new Date().toISOString(),
      password: bcrypt.hashSync(process.env.ADMIN_PASSWORD || 'admin123', 10),
    },
  ];

  const categories: Category[] = [
    {
      id: 'cat_electronics',
      tenantId: 'tenant_demo',
      slug: 'electronics',
      name: 'Electronics & Audio',
      description: 'Studio-grade acoustics, mechanical keyboards, and precision tech.',
      image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
      icon: 'Headphones',
      sortOrder: 1,
      status: 'active',
    },
    {
      id: 'cat_accessories',
      tenantId: 'tenant_demo',
      slug: 'everyday-carry',
      name: 'Everyday Carry',
      description: 'Full-grain leather wallets, key organizers, and minimalist accessories.',
      image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
      icon: 'Briefcase',
      sortOrder: 2,
      status: 'active',
    },
    {
      id: 'cat_fitness',
      tenantId: 'tenant_demo',
      slug: 'fitness-outdoors',
      name: 'Fitness & Hydration',
      description: 'Insulated stainless bottles, alignment yoga mats, and active lifestyle gear.',
      image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=600&q=80',
      icon: 'Activity',
      sortOrder: 3,
      status: 'active',
    },
  ];

  const collections: Collection[] = [
    {
      id: 'col_all',
      tenantId: 'tenant_demo',
      slug: 'all-products',
      title: 'All Products',
      description: 'Browse our complete catalog of curated lifestyle and tech essentials.',
      image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
      productIds: ['prod_headphones_pro', 'prod_leather_wallet', 'prod_water_bottle', 'prod_yoga_mat', 'prod_mechanical_keyboard'],
      sortOrder: 1,
      status: 'published',
    },
    {
      id: 'col_bestsellers',
      tenantId: 'tenant_demo',
      slug: 'bestsellers',
      title: 'Best Sellers',
      description: 'Top-rated gear loved by thousands of creators and professionals worldwide.',
      image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      productIds: ['prod_headphones_pro', 'prod_leather_wallet', 'prod_mechanical_keyboard'],
      sortOrder: 2,
      status: 'published',
    },
  ];

  const products: Product[] = [
    {
      id: 'prod_headphones_pro',
      tenantId: 'tenant_demo',
      slug: 'wireless-headphones-pro',
      title: 'Wireless Active Noise-Cancelling Headphones',
      shortDescription: 'Studio-quality acoustics, 40-hour battery life, and ultra-soft memory foam earcups.',
      description: '<p>Experience immersive high-fidelity audio with hybrid active noise cancellation. Designed for creators, commuters, and audiophiles who demand flawless sound and all-day comfort.</p>',
      price: 49.99,
      compareAtPrice: 99.99,
      currency: 'USD',
      sku: 'GUM-AUD-001',
      categoryId: 'cat_electronics',
      collectionIds: ['col_all', 'col_bestsellers'],
      tags: ['audio', 'wireless', 'headphones', 'bluetooth'],
      status: 'published',
      featured: true,
      bestseller: true,
      newProduct: false,
      sale: true,
      images: [
        'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1000&q=80',
        'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=1000&q=80',
      ],
      thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
      specifications: [
        { key: 'Battery Life', value: '40 Hours Playtime' },
        { key: 'Connectivity', value: 'Bluetooth 5.3 + 3.5mm Aux' },
        { key: 'Drivers', value: '40mm Custom Neodymium' },
        { key: 'Weight', value: '240g' },
      ],
      faq: [
        { question: 'Does this come with a carrying case?', answer: 'Yes, a custom hard-shell travel case and USB-C fast charging cable are included.' },
        { question: 'Is there a warranty?', answer: 'All GumShop hardware includes a 1-year comprehensive manufacturer warranty.' },
      ],
      gumroadUrl: '',
      primaryCheckout: 'gumroad',
      directCheckout: true,
      buttonText: 'Buy Now - Free Shipping',
      sortOrder: 1,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod_leather_wallet',
      tenantId: 'tenant_demo',
      slug: 'minimalist-leather-wallet',
      title: 'Slim RFID-Blocking Full-Grain Leather Wallet',
      shortDescription: 'Ultra-compact front-pocket design crafted from premium vegetable-tanned leather.',
      description: '<p>Streamline your everyday carry. Holds up to 10 cards and cash securely while protecting your RFID-enabled cards from unauthorized wireless scanning.</p>',
      price: 29.99,
      compareAtPrice: 59.99,
      currency: 'USD',
      sku: 'GUM-ACC-002',
      categoryId: 'cat_accessories',
      collectionIds: ['col_all', 'col_bestsellers'],
      tags: ['leather', 'wallet', 'minimalist', 'edc'],
      status: 'published',
      featured: true,
      bestseller: true,
      newProduct: false,
      sale: true,
      images: [
        'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=1000&q=80',
        'https://images.unsplash.com/photo-1554412933-514a83d2f3c8?auto=format&fit=crop&w=1000&q=80',
      ],
      thumbnail: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=600&q=80',
      specifications: [
        { key: 'Material', value: '100% Full-Grain Leather' },
        { key: 'Card Capacity', value: '8-10 Cards + Cash Clip' },
        { key: 'Protection', value: 'RFID / NFC Shielding' },
      ],
      faq: [
        { question: 'Will this fit comfortably in front pockets?', answer: 'Yes, it measures just 0.4 inches thin and is optimized specifically for front-pocket carry.' },
      ],
      gumroadUrl: '',
      primaryCheckout: 'gumroad',
      directCheckout: true,
      buttonText: 'Buy Now - Free Shipping',
      sortOrder: 2,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod_water_bottle',
      tenantId: 'tenant_demo',
      slug: 'insulated-stainless-bottle',
      title: 'Matte Vacuum-Insulated Stainless Steel Bottle (32oz)',
      shortDescription: 'Keeps drinks ice cold for 24 hours or piping hot for 12 hours with double-wall insulation.',
      description: '<p>Built from food-grade 18/8 stainless steel with a sweat-proof matte powder coat finish. Leak-proof spout lid included.</p>',
      price: 24.99,
      compareAtPrice: 49.99,
      currency: 'USD',
      sku: 'GUM-FIT-003',
      categoryId: 'cat_fitness',
      collectionIds: ['col_all'],
      tags: ['bottle', 'stainless', 'hydration', 'fitness'],
      status: 'published',
      featured: false,
      bestseller: false,
      newProduct: true,
      sale: true,
      images: [
        'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=1000&q=80',
      ],
      thumbnail: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80',
      specifications: [
        { key: 'Capacity', value: '32 oz / 950 ml' },
        { key: 'Insulation', value: 'Double-Wall Vacuum' },
        { key: 'Material', value: 'Food-Grade 18/8 Stainless Steel' },
      ],
      faq: [
        { question: 'Is it dishwasher safe?', answer: 'Yes, the bottle and lid are top-rack dishwasher safe.' },
      ],
      gumroadUrl: '',
      primaryCheckout: 'gumroad',
      directCheckout: true,
      buttonText: 'Buy Now - Free Shipping',
      sortOrder: 3,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod_yoga_mat',
      tenantId: 'tenant_demo',
      slug: 'eco-grip-yoga-mat',
      title: 'Eco-Grip Non-Slip Alignment Yoga Mat (6mm)',
      shortDescription: 'High-density natural rubber with laser-etched body alignment guides for peak stability.',
      description: '<p>Engineered for sweat-resistant grip and premium joint cushioning. Non-toxic, biodegradable, and free from PVC and harsh chemicals.</p>',
      price: 34.99,
      compareAtPrice: 69.99,
      currency: 'USD',
      sku: 'GUM-FIT-004',
      categoryId: 'cat_fitness',
      collectionIds: ['col_all'],
      tags: ['yoga', 'fitness', 'mat', 'exercise'],
      status: 'published',
      featured: false,
      bestseller: false,
      newProduct: false,
      sale: true,
      images: [
        'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=1000&q=80',
      ],
      thumbnail: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=600&q=80',
      specifications: [
        { key: 'Thickness', value: '6mm High-Density' },
        { key: 'Dimensions', value: '72" L x 26" W' },
        { key: 'Weight', value: '2.4 kg' },
      ],
      faq: [
        { question: 'Does it come with a carrying strap?', answer: 'Yes, a premium cotton carrying sling is included with every mat.' },
      ],
      gumroadUrl: '',
      primaryCheckout: 'gumroad',
      directCheckout: true,
      buttonText: 'Buy Now - Free Shipping',
      sortOrder: 4,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod_mechanical_keyboard',
      tenantId: 'tenant_demo',
      slug: 'rgb-mechanical-keyboard',
      title: 'Compact 75% Wireless Mechanical Keyboard',
      shortDescription: 'Hot-swappable tactile switches, per-key RGB backlighting, and CNC aluminum casing.',
      description: '<p>Elevate your workspace. Features tri-mode connectivity (Bluetooth 5.1, 2.4GHz wireless, USB-C), sound-dampening silicone pads, and cross-platform Mac/Windows support.</p>',
      price: 79.99,
      compareAtPrice: 159.99,
      currency: 'USD',
      sku: 'GUM-TECH-005',
      categoryId: 'cat_electronics',
      collectionIds: ['col_all', 'col_bestsellers'],
      tags: ['keyboard', 'wireless', 'mechanical', 'rgb', 'gaming'],
      status: 'published',
      featured: true,
      bestseller: true,
      newProduct: true,
      sale: true,
      images: [
        'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1000&q=80',
        'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=1000&q=80',
      ],
      thumbnail: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
      specifications: [
        { key: 'Switches', value: 'Gateron Pro Brown (Tactile)' },
        { key: 'Layout', value: '75% ANSI (84 Keys)' },
        { key: 'Battery', value: '4000 mAh Rechargeable' },
      ],
      faq: [
        { question: 'Is this hot-swappable?', answer: 'Yes, full 5-pin and 3-pin hot-swappable PCB support with no soldering required.' },
      ],
      gumroadUrl: '',
      primaryCheckout: 'gumroad',
      directCheckout: true,
      buttonText: 'Buy Now - Free Shipping',
      sortOrder: 5,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  const bundles: Bundle[] = [
    {
      id: 'bnd_creator_desk',
      tenantId: 'tenant_demo',
      slug: 'creator-desk-kit',
      name: 'Creator Desk Setup Kit',
      description: 'Includes the Compact 75% Mechanical Keyboard + Wireless ANC Headphones at an exclusive 55% bundle discount.',
      price: 99.99,
      compareAtPrice: 259.98,
      image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1000&q=80',
      productIds: ['prod_mechanical_keyboard', 'prod_headphones_pro'],
      ctaText: 'Get Desk Setup Kit',
      gumroadUrl: '',
      status: 'published',
      sortOrder: 1,
    },
    {
      id: 'bnd_everyday_carry',
      tenantId: 'tenant_demo',
      slug: 'edc-essentials-pack',
      name: 'Daily Carry Essentials Pack',
      description: 'Pair the Slim RFID Full-Grain Leather Wallet with our 32oz Insulated Stainless Steel Bottle.',
      price: 39.99,
      compareAtPrice: 109.98,
      image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=1000&q=80',
      productIds: ['prod_leather_wallet', 'prod_water_bottle'],
      ctaText: 'Get Daily Carry Pack',
      gumroadUrl: '',
      status: 'published',
      sortOrder: 2,
    },
  ];

  const homepageSections: HomepageSection[] = [
    {
      id: 'sec_hero',
      type: 'hero',
      title: 'Crafted for Everyday Excellence',
      subtitle: 'Premium gear designed with obsession for detail, durability, and aesthetics.',
      content: 'Enjoy flat 50% launch discounts on all catalog items with free express delivery worldwide.',
      image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1600&q=80',
      buttonText: 'Shop Best Sellers',
      buttonUrl: '/collections/bestsellers',
      enabled: true,
      sortOrder: 1,
    },
    {
      id: 'sec_categories',
      type: 'categories',
      title: 'Shop by Category',
      enabled: true,
      sortOrder: 2,
    },
    {
      id: 'sec_featured_products',
      type: 'products',
      title: 'Featured Essentials',
      content: 'col_all',
      enabled: true,
      sortOrder: 3,
    },
    {
      id: 'sec_bundles',
      type: 'bundles',
      title: 'Exclusive Bundle Deals',
      content: 'Save up to 55% when you bundle complementary hardware and everyday carry items together.',
      enabled: true,
      sortOrder: 4,
    },
  ];

  const navigationItems: NavigationItem[] = [
    { id: 'nav_all', label: 'All Products', url: '/collections/all', sortOrder: 1, openNewTab: false, visible: true },
    { id: 'nav_bestsellers', label: 'Best Sellers', url: '/collections/bestsellers', sortOrder: 2, openNewTab: false, visible: true },
    { id: 'nav_bundles', label: 'Bundles & Kits', url: '/bundles', sortOrder: 3, openNewTab: false, visible: true },
    { id: 'nav_about', label: 'About Us', url: '/about', sortOrder: 4, openNewTab: false, visible: true },
    { id: 'nav_contact', label: 'Support', url: '/contact', sortOrder: 5, openNewTab: false, visible: true },
  ];

  const footerColumns: FooterColumn[] = [
    {
      id: 'col_shop',
      title: 'Shop',
      sortOrder: 1,
      links: [
        { id: 'fl_all', label: 'All Products', url: '/collections/all' },
        { id: 'fl_best', label: 'Best Sellers', url: '/collections/bestsellers' },
        { id: 'fl_bun', label: 'Bundles & Deals', url: '/bundles' },
      ],
    },
    {
      id: 'col_company',
      title: 'Company',
      sortOrder: 2,
      links: [
        { id: 'fl_abt', label: 'About Us', url: '/about' },
        { id: 'fl_cnt', label: 'Contact & Support', url: '/contact' },
        { id: 'fl_blg', label: 'Store Blog', url: '/blog' },
      ],
    },
    {
      id: 'col_cust',
      title: 'Customer Service',
      sortOrder: 3,
      links: [
        { id: 'fl_shp', label: 'Shipping & Delivery', url: '/contact' },
        { id: 'fl_trk', label: 'Track My Order', url: '/contact' },
        { id: 'fl_ret', label: 'Returns & Warranty', url: '/contact' },
      ],
    },
  ];

  const themeSettings: ThemeSettings = {
    brandName: 'GumShop',
    tagline: 'Premium Gear, Minimalist Living',
    logoUrl: '',
    faviconUrl: '',
    primaryColor: '#6366F1',
    secondaryColor: '#4F46E5',
    accentColor: '#10B981',
    backgroundColor: '#0A0C0F',
    surfaceColor: '#14171F',
    textColor: '#F3F4F6',
    mutedTextColor: '#9CA3AF',
    buttonColor: '#6366F1',
    buttonTextColor: '#FFFFFF',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    headingWeight: '800',
    bodyWeight: '400',
    maxWidth: '1280px',
    borderRadius: '16px',
    cardRadius: '16px',
    buttonRadius: '12px',
    sectionSpacing: '80px',
    gridGap: '24px',
    stickyHeader: true,
    transparentHeader: true,
    logoPosition: 'left',
    navigationPosition: 'left',
    announcementEnabled: true,
    announcementText: '? Flash Sale: 50% Off Everything Today + Free Worldwide Express Shipping',
    announcementLink: '/collections/all',
    announcementBg: '#4F46E5',
    announcementColor: '#FFFFFF',
    footerColumnsCount: 3,
    footerBg: '#090B0E',
    footerTextColor: '#9CA3AF',
    copyrightText: '? 2026 GumShop. All rights reserved.',
    socialLinks: {
      x: 'https://x.com',
      youtube: 'https://youtube.com',
    },
  };

  const paymentIntegrations: PaymentIntegration[] = [
    {
      id: 'pay_gumroad',
      provider: 'gumroad',
      label: 'Gumroad Payments',
      enabled: true,
      storeUrl: 'https://manmeetraj6.gumroad.com',
      buttonText: 'Buy Now - Free Shipping',
      checkoutMode: 'overlay',
      openNewTab: true,
      settingsJson: {
        accessToken: '',
        prefillEmail: true,
      },
    },
  ];

    const promotions: Promotion[] = [
    {
      id: 'promo_welcome',
      type: 'popup',
      title: 'Get 50% Off Your First Order',
      description: 'Enter your email to receive our flash sale bundle discounts.',
      discountCode: 'GUM50',
      discountType: 'percentage',
      discountValue: 50,
      enabled: true,
    },
    {
      id: 'promo_save10',
      type: 'discount_code',
      title: '$10 Off Orders Over $50',
      description: 'Save $10 on orders over $50.',
      discountCode: 'SAVE10',
      discountType: 'fixed_amount',
      discountValue: 10,
      minSpend: 50,
      enabled: true,
    },
    {
      id: 'promo_vip20',
      type: 'discount_code',
      title: 'VIP 20% Off',
      description: 'Take 20% off your entire cart.',
      discountCode: 'VIP20',
      discountType: 'percentage',
      discountValue: 20,
      enabled: true,
    },
  ];

  const testimonials: Testimonial[] = [
    {
      id: 'test_1',
      name: 'Marcus Vance',
      title: 'Audio Engineer',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      review: 'The ANC Wireless Headphones blew away my expectations. Studio-accurate bass and the build quality feels like a $300 unit.',
      rating: 5,
      verified: true,
      published: true,
      sortOrder: 1,
    },
    {
      id: 'test_2',
      name: 'Elena Rostova',
      title: 'Digital Nomad & Designer',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      review: 'I love how slim the RFID leather wallet is. Fits seamlessly into front pockets and the leather patina after 2 months is stunning.',
      rating: 5,
      verified: true,
      published: true,
      sortOrder: 2,
    },
  ];

  const blogPosts: BlogPost[] = [
    {
      id: 'post_desk_setup',
      slug: 'how-to-build-the-ultimate-minimalist-desk-setup',
      title: 'How to Build the Ultimate Minimalist Workspace for Focus & Flow',
      excerpt: 'Tips and hardware essentials to streamline your desk and boost creative productivity.',
      content: '<p>A clean desk leads to a clear mind. Here are the 5 core hardware choices that eliminate clutter and enhance ergonomics...</p>',
      author: 'GumShop Team',
      featuredImage: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80',
      categories: ['Workspace'],
      tags: ['productivity', 'hardware', 'workspace'],
      readTime: '4 min read',
      status: 'published',
      publishedAt: new Date().toISOString(),
    },
  ];

  const siteSettings: SiteSettings = {
    currency: 'USD',
    currencySymbol: '$',
    maintenanceMode: false,
    maintenanceTitle: 'Store Under Maintenance',
    maintenanceMessage: 'We are updating our catalog. Please check back shortly.',
    newsletterProvider: 'custom',
    newsletterHeadline: 'Get 50% Off Your First Order',
    newsletterDescription: 'Join 10,000+ creators getting exclusive gear discounts.',
    newsletterSuccessMsg: 'Welcome aboard! Check your inbox for your 50% off promo code.',
    contactEmail: 'support@gumshop.online',
    seoTitle: 'GumShop ? Premium Lifestyle & Tech Gear',
    seoDescription: 'Launch your store and shop curated tech, everyday carry, and fitness gear.',
    ogImage: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80',
    twitterCard: 'summary_large_image',
    canonicalUrl: 'https://gumshop.online',
    googleAnalyticsId: 'G-70Y6ESKK1X',
    googleSearchConsoleTag: 'googleb95b120fbad0cb5e',
  };

  return {
    tenants: [tenantDemo],
    users,
    categories,
    collections,
    products,
    bundles,
    homepageSections,
    navigationItems,
    footerColumns,
    themeSettings,
    paymentIntegrations,
    promotions,
    testimonials,
    blogPosts,
    siteSettings,
    orders: [],
    analyticsEvents: [],
    mediaItems: [],
    adminActivity: [],
  };
}
