import { ThemeSettings } from '../types';

export interface ThemePreset {
  id: string;
  name: string;
  category: 'tech' | 'fashion' | 'wellness' | 'digital' | 'gaming' | 'food' | 'home' | 'streetwear';
  categoryLabel: string;
  description: string;
  icon: string;
  badge?: string;
  previewColors: string[]; // 4 color swatches: [bg, surface, accent, button]
  settings: Partial<ThemeSettings>;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'cyber-tech',
    name: 'Cyber Tech & Minimal EDC',
    category: 'tech',
    categoryLabel: 'Tech & Gadgets',
    description: 'Stealth dark background with vibrant indigo and violet accents. Engineered for precision electronics, mechanical keyboards, and studio audio gear.',
    icon: '⚡',
    badge: 'Popular',
    previewColors: ['#0A0C0F', '#14171F', '#6366F1', '#4F46E5'],
    settings: {
      brandName: 'AudioGear & Minimalist EDC',
      tagline: 'Curated everyday carry essentials & studio-grade acoustics.',
      primaryColor: '#0A0C0F',
      secondaryColor: '#14171F',
      accentColor: '#6366F1',
      backgroundColor: '#0A0C0F',
      surfaceColor: '#14171F',
      textColor: '#F9FAFB',
      mutedTextColor: '#9CA3AF',
      buttonColor: '#6366F1',
      buttonTextColor: '#FFFFFF',
      buttonRadius: '10px',
      cardRadius: '16px',
      announcementBg: '#4F46E5',
      announcementText: '⚡ FLASH SALE: Use code GEAR20 for 20% off all studio acoustics',
    },
  },
  {
    id: 'luxury-fashion',
    name: 'Luxury Fashion & Haute Apparel',
    category: 'fashion',
    categoryLabel: 'Fashion & Jewelry',
    description: 'Ultra-deep onyx aesthetic with warm champagne gold accents and razor-sharp borders. Perfect for designer clothing, fine jewelry, and luxury watches.',
    icon: '✨',
    badge: 'Luxury',
    previewColors: ['#080808', '#121212', '#D4AF37', '#D4AF37'],
    settings: {
      brandName: 'MAISON NOIR',
      tagline: 'Haute couture & artisan crafted jewelry essentials.',
      primaryColor: '#080808',
      secondaryColor: '#121212',
      accentColor: '#D4AF37',
      backgroundColor: '#080808',
      surfaceColor: '#121212',
      textColor: '#FFFFFF',
      mutedTextColor: '#A3A3A3',
      buttonColor: '#D4AF37',
      buttonTextColor: '#080808',
      buttonRadius: '4px',
      cardRadius: '6px',
      announcementBg: '#D4AF37',
      announcementText: 'COMPLIMENTARY WORLDWIDE EXPRESS SHIPPING ON ALL ORDERS OVER $200',
    },
  },
  {
    id: 'organic-wellness',
    name: 'Organic, Botanical & Wellness',
    category: 'wellness',
    categoryLabel: 'Health & Beauty',
    description: 'Earthy deep forest tones with soothing sage green accents and soft pill-shaped cards. Tailored for skincare, herbal teas, essential oils, and yoga brands.',
    icon: '🌿',
    previewColors: ['#0B1411', '#12201C', '#10B981', '#059669'],
    settings: {
      brandName: 'Botanica Wellness',
      tagline: '100% organic holistic skincare & cold-pressed botanicals.',
      primaryColor: '#0B1411',
      secondaryColor: '#12201C',
      accentColor: '#10B981',
      backgroundColor: '#0B1411',
      surfaceColor: '#12201C',
      textColor: '#F3F4F6',
      mutedTextColor: '#9CA3AF',
      buttonColor: '#10B981',
      buttonTextColor: '#06281E',
      buttonRadius: '24px',
      cardRadius: '20px',
      announcementBg: '#059669',
      announcementText: '🌿 Plant-Powered Formulations · Free Eco-Friendly Canvas Tote on Orders $75+',
    },
  },
  {
    id: 'digital-saas',
    name: 'Digital Creator & SaaS Assets',
    category: 'digital',
    categoryLabel: 'Digital Goods',
    description: 'Deep cosmic space navy with electric cyan highlights and subtle glassmorphic contrast. Designed for Notion templates, UI kits, icon sets, and digital downloads.',
    icon: '🚀',
    badge: 'Creator',
    previewColors: ['#090D16', '#111827', '#06B6D4', '#0891B2'],
    settings: {
      brandName: 'PixelCraft Digital Assets',
      tagline: 'Premium 3D UI kits, Figma systems, & Notion productivity packs.',
      primaryColor: '#090D16',
      secondaryColor: '#111827',
      accentColor: '#06B6D4',
      backgroundColor: '#090D16',
      surfaceColor: '#111827',
      textColor: '#F9FAFB',
      mutedTextColor: '#94A3B8',
      buttonColor: '#06B6D4',
      buttonTextColor: '#082F49',
      buttonRadius: '12px',
      cardRadius: '18px',
      announcementBg: '#0891B2',
      announcementText: '🚀 INSTANT DOWNLOAD: Access 500+ Figma components immediately after purchase',
    },
  },
  {
    id: 'gaming-anime',
    name: 'Anime, Gaming & Esports',
    category: 'gaming',
    categoryLabel: 'Gaming & Merch',
    description: 'Midnight void background infused with electric cyberpunk pink and vibrant neon yellow. Great for custom mechanical keycaps, anime apparel, and streaming gear.',
    icon: '🎮',
    previewColors: ['#0D0B18', '#18142E', '#EC4899', '#DB2777'],
    settings: {
      brandName: 'NEO-TOKYO GEAR',
      tagline: 'Custom artisan keycaps, desk mats, and anime cyberpunk apparel.',
      primaryColor: '#0D0B18',
      secondaryColor: '#18142E',
      accentColor: '#EC4899',
      backgroundColor: '#0D0B18',
      surfaceColor: '#18142E',
      textColor: '#FFFFFF',
      mutedTextColor: '#A5B4FC',
      buttonColor: '#EC4899',
      buttonTextColor: '#FFFFFF',
      buttonRadius: '8px',
      cardRadius: '12px',
      announcementBg: '#DB2777',
      announcementText: '🔥 LIMITED DROP: Neon Oni Keycap Set is live · Only 250 units worldwide',
    },
  },
  {
    id: 'artisan-coffee',
    name: 'Specialty Coffee & Gourmet Goods',
    category: 'food',
    categoryLabel: 'Food & Beverage',
    description: 'Rich roasted espresso dark brown with warm amber honey accents. Ideal for specialty coffee roasters, craft hot sauces, artisan bakeries, and culinary goods.',
    icon: '☕',
    previewColors: ['#120D0A', '#1C1510', '#F59E0B', '#D97706'],
    settings: {
      brandName: 'AURA ROASTERS',
      tagline: 'Single-origin specialty coffee beans roasted fresh to order.',
      primaryColor: '#120D0A',
      secondaryColor: '#1C1510',
      accentColor: '#F59E0B',
      backgroundColor: '#120D0A',
      surfaceColor: '#1C1510',
      textColor: '#FEF3C7',
      mutedTextColor: '#D1D5DB',
      buttonColor: '#F59E0B',
      buttonTextColor: '#451A03',
      buttonRadius: '12px',
      cardRadius: '16px',
      announcementBg: '#D97706',
      announcementText: '☕ Fresh Weekly Roast · Free Sample Bag Included with All Orders Over $40',
    },
  },
  {
    id: 'nordic-home',
    name: 'Nordic Minimal & Home Living',
    category: 'home',
    categoryLabel: 'Home & Decor',
    description: 'Clean charcoal slate with warm terracotta highlights and understated Scandinavian balance. Tailored for ceramic tableware, desk lamps, and interior decor.',
    icon: '🛋️',
    previewColors: ['#111317', '#1A1D23', '#F97316', '#EA580C'],
    settings: {
      brandName: 'STUDIO NORDIC',
      tagline: 'Minimalist Scandinavian furniture, ceramics, and architectural lighting.',
      primaryColor: '#111317',
      secondaryColor: '#1A1D23',
      accentColor: '#F97316',
      backgroundColor: '#111317',
      surfaceColor: '#1A1D23',
      textColor: '#F8FAFC',
      mutedTextColor: '#94A3B8',
      buttonColor: '#F97316',
      buttonTextColor: '#FFFFFF',
      buttonRadius: '10px',
      cardRadius: '14px',
      announcementBg: '#EA580C',
      announcementText: '🕊️ Autumn Collection Live: Handcrafted Stoneware & Linen Living Essentials',
    },
  },
  {
    id: 'bold-streetwear',
    name: 'Bold Streetwear & Sneaker Drops',
    category: 'streetwear',
    categoryLabel: 'Streetwear & Drops',
    description: 'Raw high-contrast pitch black with hyper volt lime neon highlights and sharp aggressive edges. Perfect for limited apparel drops, sneaker resale, and skate merch.',
    icon: '🔥',
    badge: 'Hype',
    previewColors: ['#050505', '#101010', '#84CC16', '#65A30D'],
    settings: {
      brandName: 'RAW / SUPPLY CO.',
      tagline: 'Heavyweight graphic tees, hoodies, and limited drop accessories.',
      primaryColor: '#050505',
      secondaryColor: '#101010',
      accentColor: '#84CC16',
      backgroundColor: '#050505',
      surfaceColor: '#101010',
      textColor: '#FFFFFF',
      mutedTextColor: '#737373',
      buttonColor: '#84CC16',
      buttonTextColor: '#000000',
      buttonRadius: '2px',
      cardRadius: '4px',
      announcementBg: '#65A30D',
      announcementText: '⚡ DROP 04 IS LIVE · WORLDWIDE EXPEDITED SHIPPING ON ALL APPAREL',
    },
  },
];
